# Generated by Django 2.2.5 on 2019-09-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'crimes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crimes',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('crimedate', models.DateField(blank=True, db_column='CrimeDate', null=True)),
                ('crimetime', models.TimeField(blank=True, db_column='CrimeTime', null=True)),
                ('crimecode', models.CharField(blank=True, db_column='CrimeCode', max_length=64, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=64, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=64, null=True)),
                ('inside_outside', models.CharField(blank=True, db_column='Inside_Outside', max_length=64, null=True)),
                ('weapon', models.CharField(blank=True, db_column='Weapon', max_length=64, null=True)),
                ('post', models.IntegerField(blank=True, db_column='Post', null=True)),
                ('district', models.CharField(blank=True, db_column='District', max_length=64, null=True)),
                ('neighborhood', models.CharField(blank=True, db_column='Neighborhood', max_length=64, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=8, max_digits=11, null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=8, max_digits=11, null=True)),
                ('location1', models.CharField(blank=True, db_column='Location1', max_length=64, null=True)),
                ('premise', models.CharField(blank=True, db_column='Premise', max_length=64, null=True)),
                ('vri_name1', models.CharField(blank=True, max_length=64, null=True)),
                ('total_incidents', models.IntegerField(blank=True, db_column='Total_Incidents', null=True)),
            ],
            options={
                'db_table': 'crimes',
                'managed': False,
            },
        ),
    ]
