# Generated by Django 2.2.5 on 2019-11-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0003_auto_20190927_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locationdata',
            fields=[
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('inside_outside', models.CharField(blank=True, max_length=7, null=True)),
                ('post', models.CharField(blank=True, max_length=8, null=True)),
                ('district', models.CharField(blank=True, max_length=64, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=64, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('location1', models.CharField(blank=True, max_length=48, null=True)),
                ('premise', models.CharField(blank=True, max_length=48, null=True)),
                ('vri_name1', models.CharField(blank=True, max_length=64, null=True)),
                ('locationid', models.IntegerField(db_column='locationId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LocationData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stagingtable',
            fields=[
                ('crimedate', models.DateField(blank=True, db_column='crimeDate', null=True)),
                ('crimetime', models.TimeField(blank=True, db_column='crimeTime', null=True)),
                ('crimecode', models.CharField(blank=True, db_column='crimeCode', max_length=12, null=True)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('inside_outside', models.CharField(blank=True, max_length=12, null=True)),
                ('weapon', models.CharField(blank=True, max_length=64, null=True)),
                ('post', models.CharField(blank=True, max_length=8, null=True)),
                ('district', models.CharField(blank=True, max_length=64, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=64, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('location1', models.CharField(blank=True, max_length=48, null=True)),
                ('premise', models.CharField(blank=True, max_length=48, null=True)),
                ('vri_name1', models.CharField(blank=True, max_length=64, null=True)),
                ('total_incidents', models.IntegerField(blank=True, null=True)),
                ('crimeid', models.AutoField(db_column='crimeId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'StagingTable',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Crimelocations',
        ),
    ]
